calculate_fid_stat_CIFAR10:
  args:
    num_gpus: 1
  start:
    name: compute_fid_stats
    dataset_name: cifar10_train
    IMS_PER_BATCH: 32
    img_size: 32
    NUM_WORKERS: 0
  dataset_mapper:
    name: CIFAR10DatasetMapper
    img_size: kwargs['img_size']
  GAN_metric:
    names:
    - PyTorchFIDISScore
    - TFFIDISScore
    torch_fid_stat: datasets/nas_cgan/pytorch_fid_stat/fid_stats_pytorch_{dataset_name}_{img_size}.npz
    tf_fid_stat: datasets/nas_cgan/tf_fid_stat/fid_stats_tf_{dataset_name}_{img_size}.npz
    tf_inception_model_dir: datasets/nas_cgan/tf_inception_model
